version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: akhomelab-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: akhomelab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:latest
    container_name: akhomelab-airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  jupyter:
    image: jupyter/datascience-notebook
    container_name: akhomelab-jupyter
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work

  python:
    image: python:latest
    container_name: akhomelab-python
    restart: always
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running
    volumes:
      - ./python:/app
    working_dir: /app
    depends_on:
      - postgres
      - airflow
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
